In [2]:
import cv2
import numpy as np


# 读取图片
cat = cv2.imread('./cat.jpg')
dog = cv2.imread('./dog.jpg')

print(cat.shape)
print(dog.shape)

# basic point
x = 150
y = 200

# 在做加法之前需要把图片的形状变得完全一样
# 可以通过ndarray的切片方式取出完全一样的形状
# 狗更大，所以从狗里切出猫的形状 左闭右开
new_dog = dog[0:300, :400]
# print(new_dog.shape)
# cv2.add 加法操作要求两个图片的长宽相等，通道数相同
# add的规则就是两个图对应位置的元素相加，如果超过255，全部变成255
print(cat[x:x+3, y:y+3])
print('-------------')
# print(new_dog[:3, :3])
new_img = cv2.add(cat, new_dog)
# print('-------------')
# print(new_img[:3, :3])

# 图片还可以和单个数字进行运算 加法常用
# 每个和100进行加法运算，超过255的数字，会被截断，相当于 %256

# cat += 100
# print(cat[x:x+3, y:y+3])


# 减法 substract 对应位置相应元素相减，减完小于0，则变为0 
# new_img = cv2.subtract(cat, new_dog)

# 乘法 multiply
# new_img = cv2.multiply(cat, new_dog)

# 除法 divide
# new_img = cv2.divide(cat, new_dog)

cv2.imshow('new_img', new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

(300, 400, 3)
(577, 600, 3)
[[[252 254 255]
  [252 254 255]
  [252 254 255]]

 [[252 254 254]
  [252 254 254]
  [252 254 254]]

 [[250 255 254]
  [252 254 254]
  [252 254 254]]]
-------------


In [3]:
(252 + 100)%256

96

In [5]:
# OpenCV的逻辑运算——与&或|非~异或^
# OpenCV中的逻辑运算就是对应元素进行与&或非异或
204 & 213

196

In [6]:
# opencv中的非 0反过来是255
~255

-256

In [7]:
204 ^ 213

25

In [31]:
import cv2
import numpy as np


# 读取图片
cat = cv2.imread('./cat.jpg')
lion = cv2.imread('./lion.jpg')

# print(cat.shape)
# print(lion.shape)
# 非操作 相当于255 - cat
# cat_not = cv2.bitwise_not(cat)
# cv2.imshow('not',np.hstack((cat, cat_not)))
# print(cat[:2, :2])
# print(cat_not[:2, :2])

# 与操作 图像颜色会更暗
# new_lion = lion[0:300, :400]
# 两个图片对应位置的元素进行与操作
# cat_and = cv2.bitwise_and(cat, new_lion)

# cv2.imshow('and', np.hstack((cat, cat_and)))
# print(cat[:2, :2])
# print('---------')
# print(lion[:2, :2])
# print('---------')
# print(cat_and[:2, :2])

# 或操作 图像颜色会更亮
# new_lion = lion[0:300, :400]
# 两个图片对应位置的元素进行或操作
# cat_and = cv2.bitwise_or(cat, new_lion)

# cv2.imshow('or', np.hstack((cat, lion, cat_and)))
# print(cat[:2, :2])
# print('---------')
# print(lion[:2, :2])
# print('---------')
# print(cat_and[:2, :2])

# 异或操作 图像颜色会两极化
new_lion = lion[0:300, :400]
# 两个图片对应位置的元素进行异或操作
cat_and = cv2.bitwise_xor(cat, new_lion)

cv2.imshow('xor', np.hstack((cat, lion, cat_and)))
print(cat[:2, :2])
print('---------')
print(lion[:2, :2])
print('---------')
print(cat_and[:2, :2])

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[48 24 18]
  [51 21 16]]

 [[55 25 20]
  [58 24 18]]]
---------
[[[53 62 89]
  [53 62 89]]

 [[52 61 88]
  [52 61 88]]]
---------
[[[ 5 38 75]
  [ 6 43 73]]

 [[ 3 36 76]
  [14 37 74]]]


In [29]:
18 | 89

91

# 图像的基本变换

In [27]:
import cv2
import numpy as np


src = cv2.imread('./cat.jpg')
dst = cv2.imread('./cat.jpg')

print(src.shape)
print(dst.shape)

# 把猫狗缩放大小一样 把狗缩放
# new_img1 = cv2.resize(src, (600, 450), interpolation = cv2.INTER_NEAREST)
# new_img2 = cv2.resize(src, (600, 450), interpolation = cv2.INTER_LINEAR)# 默认效果
# new_img3 = cv2.resize(src, (600, 450), interpolation = cv2.INTER_CUBIC)
# new_img4 = cv2.resize(src, (600, 450), interpolation = cv2.INTER_AREA)
# print(new_img1.shape)

# cv2.imshow('new_img1', new_img1)
# cv2.imshow('new_img2', new_img2)
# cv2.imshow('new_img3', new_img3)
# cv2.imshow('new_img4', new_img4)
# cv2.imshow('src', src)

new_img = cv2.resize(src, dsize = None, fx = 1.0, fy = 0.5, interpolation = cv2.INTER_AREA)
print(new_img.shape)
cv2.imshow('new_img', new_img)
cv2.imshow('img', src)

key = cv2.waitKey(0)        
cv2.destroyAllWindows()

(300, 400, 3)
(300, 400, 3)
(150, 400, 3)


In [6]:
# 作业练习
# 1.引入一张图片
# 2.设计一张图片
# 3.规划一下logo的位置，在添加的位置变成黑色
# 4.利用add方法，把logo和图片叠加在一起
import cv2
import numpy as np


# 导入图片
dog = cv2.imread('./cat.jpg')
# cv2.imshow('dog', dog)

# 创建LOGO
logo = np.zeros((200, 200, 3), np.uint8)

# 绘制logo
logo[20:80, 20:80] = [0, 0, 255]
logo[50:100, 50:100] = [0, 255, 0]
# cv2.imshow('logo', logo)

# 掩码
mask = np.zeros((200, 200), np.uint8)
mask[20:80, 20:80] = 255
mask[50:100, 50:100] = 255

# cv2.imshow('mask', mask)
mask_not = cv2.bitwise_not(mask)
# cv2.imshow('mask_not', mask_not)

# 选择dog添加logo的位置
roi = dog[0:200, 0:200]
# roi与mask_not进行与运算，先让roi与roi做与运算，然后结果再和mask做与运算，如果与的结果是True,那么返回原图像素，否则返回0
tmp = cv2.bitwise_and(roi, roi, mask = mask_not)
# cv2.imshow('tmp', tmp)

dst = cv2.add(tmp, logo)
# cv2.imshow('dst', dst)
# 在dog上还原
dog[0:200, :200] = dst
cv2.imshow('dogLogo', dog)

cv2.waitKey(0)
cv2.destroyAllWindows()