In [1]:
# 查看一张图片中所有的颜色数量
import cv2


lion=cv2.imread('./lion.jpg')
cv2.imshow('lion',lion)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# 想看lion中有多少种颜色
lion

array([[[ 53,  62,  89],
        [ 53,  62,  89],
        [ 53,  62,  89],
        ...,
        [ 99, 113, 149],
        [ 99, 114, 147],
        [ 98, 113, 146]],

       [[ 52,  61,  88],
        [ 52,  61,  88],
        [ 52,  61,  88],
        ...,
        [ 99, 113, 149],
        [ 98, 113, 146],
        [ 98, 113, 146]],

       [[ 51,  60,  87],
        [ 51,  60,  87],
        [ 51,  60,  87],
        ...,
        [ 98, 113, 146],
        [ 98, 113, 146],
        [ 97, 112, 145]],

       ...,

       [[ 46,  57,  85],
        [ 46,  57,  85],
        [ 45,  56,  84],
        ...,
        [ 67,  80, 106],
        [ 68,  82, 105],
        [ 69,  83, 102]],

       [[ 47,  58,  86],
        [ 47,  58,  86],
        [ 47,  58,  86],
        ...,
        [ 68,  82, 105],
        [ 70,  83, 105],
        [ 70,  84, 103]],

       [[ 49,  60,  88],
        [ 49,  60,  88],
        [ 48,  59,  87],
        ...,
        [ 70,  82, 106],
        [ 71,  84, 106],
        [ 71,  85, 104]]

In [3]:
from pandas import DataFrame


# 用每一个像素创建dataframe
df = DataFrame(lion.reshape(-1,3))

df.head()

ModuleNotFoundError: No module named 'pandas'

In [ ]:
df.shape

In [6]:
160200 - df.duplicated().sum()

31802

In [ ]:
# 关键API cv2.cvtColor
import cv2

def callback(value):
    pass

cv2.namedWindow('color',cv2.WINDOW_NORMAL)
cv2.resizeWindow('color',534,360)

# 读取图片，opencv读进来的图片默认是BGR的色彩空间
img = cv2.imread('./lion.jpg')

# 定义颜色空间转化列表
color_spaces = [
    # 所有颜色空间的转化都是COLOR开头的
    cv2.COLOR_BGR2RGBA, cv2.COLOR_BGR2BGRA,
    cv2.COLOR_BGR2GRAY, cv2.COLOR_BGR2HSV,
    cv2.COLOR_BGR2YUV
]

# 设置trackbar
cv2.createTrackbar('trackbar', 'color', 0, 4, callback)

while True:
    # 获取trackbar的值
    index = cv2.getTrackbarPos('trackbar', 'color')
    
    # 进行颜色转化
    cvt_img = cv2.cvtColor(img, color_spaces[index])

    cv2.imshow('color',cvt_img)
    key = cv2.waitKey(100)
    if key == ord('q'):
        break
    
cv2.destroyAllWindows()

In [8]:
# opencv用mat这种数据结构来表示图片的
# c++ 中用mat来保存图片。python中把mat转化成了numpy的ndarray
# cv2.imshow()
img

array([[[ 53,  62,  89],
        [ 53,  62,  89],
        [ 53,  62,  89],
        ...,
        [ 99, 113, 149],
        [ 99, 114, 147],
        [ 98, 113, 146]],

       [[ 52,  61,  88],
        [ 52,  61,  88],
        [ 52,  61,  88],
        ...,
        [ 99, 113, 149],
        [ 98, 113, 146],
        [ 98, 113, 146]],

       [[ 51,  60,  87],
        [ 51,  60,  87],
        [ 51,  60,  87],
        ...,
        [ 98, 113, 146],
        [ 98, 113, 146],
        [ 97, 112, 145]],

       ...,

       [[ 46,  57,  85],
        [ 46,  57,  85],
        [ 45,  56,  84],
        ...,
        [ 67,  80, 106],
        [ 68,  82, 105],
        [ 69,  83, 102]],

       [[ 47,  58,  86],
        [ 47,  58,  86],
        [ 47,  58,  86],
        ...,
        [ 68,  82, 105],
        [ 70,  83, 105],
        [ 70,  84, 103]],

       [[ 49,  60,  88],
        [ 49,  60,  88],
        [ 48,  59,  87],
        ...,
        [ 70,  82, 106],
        [ 71,  84, 106],
        [ 71,  85, 104]]

In [9]:
type(img)

numpy.ndarray

In [10]:
# ndarray4种常见属性？

img.data

In [11]:
import numpy as np

one = np.ones((2,3))

In [12]:
one.data

In [13]:
# 元素总个数
img.size

480600

In [14]:
img.dtype

dtype('uint8')

In [15]:
img.shape

(300, 534, 3)

In [16]:
img.itemsize

1

In [17]:
img.ndim

3

In [19]:
img.imag

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [23]:
# 因为python中图片数据已经包装成ndarray,所以对mat的深浅拷贝，其实就是堆ndarray深浅拷贝
import cv2
import numpy as np

img = cv2.imread('lion.jpg')

# 浅拷贝
img2 = img.view()

# 深拷贝
img3 = img.copy()

img[10:100, 10:100] = [0, 0, 255]

# 横排合放
cv2.imshow('img', np.hstack((img, img2, img3)))
# cv2.imshow('img',img)
# cv2.imshow('img2',img2)
# cv2.imshow('img3',img3)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
# 图像的分割与融合
import cv2
import numpy as np

img = np.zeros((200, 200, 3), np.uint8)
# 个人添加的分割线
img[99:100, 0:200] = [255, 255, 255]
img[0:200, 199:200] = [255, 255, 255]
# 分隔通道
b,g,r = cv2.split(img)
# 修改一些颜色
b[10:100, 10:100] = 255
g[10:100, 10:100] = 255

print('b', b)
# 合并通道
img2 = cv2.merge((b,g,r))

cv2.imshow('img', np.hstack((b, g)))
cv2.imshow('img2', np.hstack((img, img2)))

cv2.waitKey(0)
cv2.destroyAllWindows()

b [[  0   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0 255]
 ...
 [  0   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0 255]]


In [14]:
# 绘制各种图形
import cv2
import numpy as np


# 创建纯黑的背景图用来画图形
img = np.zeros((480, 640, 3), np.uint8)

# line(img,pt1,pt2,color,thickness,lineType,shift)
# cv2.line(img, (10,20), (300,400), (0, 0, 255), 5, 4 )
# cv2.line(img, (90,100), (380,480), (0, 0, 255), 5, 16 )
# cv2.rectangle(img, (80,80), (380,380), (0, 255, 0), 5)

# 画圆 需要圆心坐标，半径大小
# cv2.circle(img, (320, 240), 50, (0, 0, 255), 5, 16)

# ellipse(img, 中心点, 长宽的一半, 角度, 从哪个角度开始, 从哪个角度结束,...)
# axes -> axis
# cv2.ellipse(img, (320, 240), (100, 50), 0, 0, 240,[0, 0, 255], 5, 16)
# 绘制多边形
# pts多边形的点集，必须是int32位
# pts = np.array([(250, 100), (150, 300), (50, 100)], np.int32)
# 注意pts是三维的 True表示闭合 False表示不闭合
# cv2.polylines(img, [pts], True, (0, 0, 255), 5)

# 填充多边形
# cv2.fillPoly(img, [pts], (0, 0, 255))
# cv2.fillConvexPoly()
# 绘制文本
for i in range(10):
    cv2.line(img, (0, i*100), (640, i*100), (255, 255, 255), 1, 4)
cv2.putText(img, 'Hello OpenCV', (50, 400), cv2.FONT_HERSHEY_COMPLEX, 2, [0, 0, 255])

cv2.imshow('draw', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
# 使用OpenCV绘制中文
# 曲线救国，OpenCV是没有办法直接绘制中文
# 使用Pillow包 安装pip install pillow
from PIL import ImageFont, ImageDraw, Image

# 纯白
# img = np.full((500, 450, 3), fill_value = 255, dtype = np.uint8)
img = cv2.imread('./lion.jpg')
# 导入字体文件
font = ImageFont.truetype('./msyhbd.ttc', 35)

# 创建一个pillow的图片
img_pil = Image.fromarray(img)

draw = ImageDraw.Draw(img_pil)
# 利用draw去绘制中文
draw.text((100, 250), '你好我好大家好',font = font, fill = (255, 0, 0, 0))

# 重新变回ndarray
img = np.array(img_pil)

cv2.imshow('img', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
import cv2
import numpy as np

curshape = 0
startpos = (0, 0)

img = np.zeros((480, 640, 3), np.uint8)


def mouse_callback(event, x, y, flags, userdata):
    if event == cv2.EVENT_LBUTTONDOWN:
        # 引入全局变量
        global curshape, startpos
        # 引入非本层的局部变量用什么关键字 nonlocal
        startpos = (x, y)
    elif event == cv2.EVENT_LBUTTONUP:
        if curshape ==0:
            cv2.line(img, startpos, (x, y), (0, 0, 255), 3)
        elif curshape == 1:
            cv2.rectangle(img, startpos, (x, y), (0, 0, 255), 3)
        elif curshape == 2:
            a = (x - startpos[0])
            b = (y - startpos[1])
            r = int((a ** 2 + b ** 2) ** 0.5)
            print(r)
            cv2.circle(img, startpos, r, (0, 0, 255), 3)
        else:
            print('暂不支持绘制其它图形')
            
cv2.namedWindow('drawshape', cv2.WINDOW_NORMAL)
cv2.setMouseCallback('drawshape', mouse_callback)

while True:
    cv2.imshow('drawshape', img)
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
    elif key == ord('l'):
        curshape = 0
    elif key == ord('r'):
        curshape = 1
    elif key == ord('c'):
        curshape = 2
        
cv2.destroyAllWindows()

235
47
